name: openirn
description: OpenIRN - application open source d’exploration et d’évaluation de l’Indice de Résilience Numérique.
publish_to: 'none'

version: 0.5.0+5

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.3
  file_selector: ^1.0.4
  package_info_plus: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
