name: Test OpenIRN Artifact Signing

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-sign:
    runs-on: windows-2025

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop

      - name: Show repository layout
        shell: powershell
        run: |
          Write-Host "Current directory:"
          Get-Location

          Write-Host "`nFlutter projects found:"
          Get-ChildItem -Path . -Filter pubspec.yaml -Recurse |
            Select-Object FullName

      - name: Dependencies
        run: flutter pub get

      - name: Build Windows
        run: flutter build windows --release

      - name: Azure login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Sign OpenIRN executable
        uses: azure/artifact-signing-action@v2
        with:
          endpoint: https://neu.codesigning.azure.net/
          signing-account-name: openirnsign
          certificate-profile-name: openirn-public

          files: ${{ github.workspace }}\build\windows\x64\runner\Release\openirn.exe

          file-digest: SHA256
          timestamp-rfc3161: http://timestamp.acs.microsoft.com
          timestamp-digest: SHA256

          exclude-environment-credential: true
          exclude-workload-identity-credential: true
          exclude-managed-identity-credential: true
          exclude-shared-token-cache-credential: true
          exclude-visual-studio-credential: true
          exclude-visual-studio-code-credential: true
          exclude-azure-cli-credential: false
          exclude-azure-powershell-credential: true
          exclude-azure-developer-cli-credential: true
          exclude-interactive-browser-credential: true

      - name: Verify signature
        shell: powershell
        run: |
          $file = "${{ github.workspace }}\build\windows\x64\runner\Release\openirn.exe"

          $sig = Get-AuthenticodeSignature $file

          Write-Host "Status  :" $sig.Status
          Write-Host "Subject :" $sig.SignerCertificate.Subject
          Write-Host "Issuer  :" $sig.SignerCertificate.Issuer

          if ($sig.Status -ne "Valid") {
            throw "OpenIRN signature is not valid"
          }

      - name: Upload signed executable
        uses: actions/upload-artifact@v4
        with:
          name: openirn-signed-test
          path: build/windows/x64/runner/Release/openirn.exe
